name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: ghcr.io/hexne/modforge/gcc-latest-docker:latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure
        run: cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
